import test from 'node:test';
import assert from 'node:assert/strict';
import { lstat, mkdir, mkdtemp, rename, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { walk, sameDevice } from '../../dist/src/fs/walk.js';
import { scanProject } from '../../dist/src/node/index.js';
import { jsonReport } from '../../dist/src/reporters/json.js';
import { checkedRead, ReadError } from '../../dist/src/fs/read.js';

test('supported candidate and config-tree links make project coverage partial while unrelated links skip normally',async()=>{const root=await mkdtemp(join(tmpdir(),'agentfence-walk-')),outside=await mkdtemp(join(tmpdir(),'agentfence-outside-'));try{await writeFile(join(outside,'config'),'{}');await symlink(join(outside,'config'),join(root,'.mcp.json'));const candidate=await walk(root);assert.equal(candidate.limited,true);assert.equal(candidate.skipped['supported-link'],1);await rm(join(root,'.mcp.json'));await symlink(join(outside,'config'),join(root,'ordinary-link'));const ordinary=await walk(root);assert.equal(ordinary.limited,false);assert.equal(ordinary.skipped.link,1);await rm(join(root,'ordinary-link'));await symlink(outside,join(root,'.claude'));const tree=await walk(root);assert.equal(tree.limited,true);assert.equal(tree.skipped['supported-link'],1);}finally{await rm(root,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}});
test('cross-device descent helper is conservative',()=>{assert.equal(sameDevice(7,7),true);assert.equal(sameDevice(7,8),false);});
test('cross-device regular candidates are skipped before acquisition while same-device reads still work',async()=>{const root=await mkdtemp(join(tmpdir(),'agentfence-cross-device-')),target=join(root,'AGENTS.md'),canary='CROSS_DEVICE_REGULAR_CANARY';try{await writeFile(target,canary);const mismatched=async path=>{const entry=await lstat(path);return path===target?new Proxy(entry,{get:(value,key,receiver)=>key==='dev'?value.dev+1:Reflect.get(value,key,receiver)}):entry;},walked=await walk(root,{lstat:mismatched});assert.equal(walked.files.includes('AGENTS.md'),false);assert.equal(walked.limited,true);assert.equal(walked.skipped['cross-device'],1);let readStarted=false;await assert.rejects(checkedRead(root,'AGENTS.md',{lstat:mismatched,afterRead:()=>{readStarted=true;}}),error=>error instanceof ReadError&&error.code==='AF_READ_REJECTED');assert.equal(readStarted,false);assert.equal(await checkedRead(root,'AGENTS.md'),canary);}finally{await rm(root,{recursive:true,force:true});}});
test('user config symlink ancestors are partial and never leak outside content',async()=>{const home=await mkdtemp(join(tmpdir(),'agentfence-home-')),outside=await mkdtemp(join(tmpdir(),'agentfence-outside-'));try{await mkdir(join(outside,'rules'));await writeFile(join(outside,'rules','escaped.md'),'USER_OUTSIDE_CANARY');await writeFile(join(outside,'config.toml'),'FIXED_USER_OUTSIDE_CANARY');await symlink(outside,join(home,'.claude'));await symlink(outside,join(home,'.codex'));const report=await scanProject({path:resolve('test/fixtures/clean'),userConfigs:true},{home:()=>home});assert.equal(report.status,'partial');assert.ok(report.errors.some(error=>error.code==='AF_USER_TREE_UNSAFE'||error.code==='AF_USER_SOURCE_UNSAFE'));const output=jsonReport(report);assert.equal(output.includes('USER_OUTSIDE_CANARY'),false);assert.equal(output.includes('FIXED_USER_OUTSIDE_CANARY'),false);}finally{await rm(home,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}});
test('git is a fixed exclusion and is never descended as a candidate tree',async()=>{const root=await mkdtemp(join(tmpdir(),'agentfence-git-'));try{await mkdir(join(root,'.git','nested'),{recursive:true});await writeFile(join(root,'.git','nested','AGENTS.md'),'GIT_CANARY');await writeFile(join(root,'AGENTS.md'),'ordinary');const result=await walk(root);assert.equal(result.files.some(path=>path.startsWith('.git/')),false);assert.ok((result.skipped.excluded??0)>=1);const report=await scanProject({path:root});assert.equal(report.errors.some(error=>error.code==='AF_WALK_LIMIT'),false);assert.equal(jsonReport(report).includes('GIT_CANARY'),false);}finally{await rm(root,{recursive:true,force:true});}});
test('checked read rejects ancestor identity swaps after opening and never returns escaped bytes',async()=>{const root=await mkdtemp(join(tmpdir(),'agentfence-read-root-')),outside=await mkdtemp(join(tmpdir(),'agentfence-read-outside-'));try{await mkdir(join(root,'safe'));await writeFile(join(root,'safe','AGENTS.md'),'inside');await writeFile(join(outside,'AGENTS.md'),'READ_ESCAPE_CANARY');await assert.rejects(checkedRead(root,'safe/AGENTS.md',{afterRead:async()=>{await rename(join(root,'safe'),join(root,'old-safe'));await symlink(outside,join(root,'safe'));}}),error=>error instanceof ReadError&&error.code==='AF_FILE_CHANGED');}finally{await rm(root,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}});
