export type Severity = 'info' | 'low' | 'medium' | 'high' | 'critical';
export type Confidence = 'high' | 'medium' | 'low';
export type Applicability = 'potential' | 'inactive' | 'unknown';
export type Scope = 'project' | 'user';
export type AgentKind = 'codex' | 'claude-code' | 'cursor' | 'kiro' | 'vscode' | 'generic-mcp';
export type Category = 'secrets' | 'shell' | 'filesystem' | 'network' | 'mcp' | 'agent-config' | 'supply-chain' | 'unicode' | 'permissions' | 'prompt-security';
export type SafeText = string & { readonly __safeText: unique symbol };
export interface Location { readonly sourceId: string; readonly scope: Scope; readonly displayPath: SafeText; readonly line?: number; readonly column?: number; readonly endLine?: number; readonly endColumn?: number; readonly field?: SafeText; }
export interface Evidence { readonly kind: 'field' | 'token-pattern' | 'instruction-pattern' | 'unicode' | 'combination'; readonly summary: SafeText; readonly factIds: readonly string[]; readonly knownEnvNames?: readonly SafeText[]; readonly codePoints?: readonly SafeText[]; }
export interface Finding { readonly id: string; readonly ruleId: string; readonly ruleVersion: string; readonly title: SafeText; readonly severity: Severity; readonly category: Category; readonly description: SafeText; readonly evidence: Evidence; readonly location: Location; readonly relatedLocations: readonly Location[]; readonly recommendation: SafeText; readonly confidence: Confidence; readonly applicability: Applicability; readonly agentIds: readonly string[]; readonly principalId?: string; readonly riskKey: string; readonly references: readonly string[]; readonly relatedFindingIds: readonly string[]; }
export interface DetectedAgent { readonly id: string; readonly kind: AgentKind; readonly detection: 'confirmed-config' | 'possible'; readonly sources: readonly string[]; readonly adapterVersion: string; readonly runtimeVersion: 'unknown'; readonly effectiveState: 'unverified'; }
export interface MCPServer { readonly id: string; readonly agentId: string; readonly principalId: string; readonly location: Location; readonly transport: 'stdio' | 'http' | 'sse' | 'unknown'; readonly enabled: 'yes' | 'no' | 'unknown'; readonly launcher: 'direct' | 'shell' | 'package-runner' | 'unknown'; readonly packageSelector: 'exact' | 'mutable' | 'absent' | 'unresolved'; readonly endpoint?: { readonly scheme: 'https' | 'http' | 'other'; readonly hostClass: 'loopback-literal' | 'private-literal' | 'other' | 'unresolved' }; readonly envBindings: readonly { readonly name: SafeText; readonly mode: 'literal' | 'reference' | 'unknown' }[]; readonly roots: readonly { readonly class: 'project' | 'home' | 'filesystem' | 'sensitive' | 'other' | 'unknown' }[]; readonly capabilityIds: readonly string[]; }
export interface Capability { readonly id: string; readonly principalId: string; readonly kind: 'process-launch' | 'shell' | 'network' | 'sensitive-env' | 'filesystem-read' | 'filesystem-write' | 'approval-bypass'; readonly basis: 'explicit-config' | 'recognized-command' | 'text-request' | 'inferred'; readonly confidence: Confidence; readonly applicability: Applicability; readonly sourceIds: readonly string[]; readonly constraints: readonly SafeText[]; }
export interface ScanError { readonly code: string; readonly stage: 'discovery' | 'read' | 'parse' | 'analyze' | 'report'; readonly sourceId?: string; readonly message: SafeText; readonly effect: 'partial' | 'fatal'; readonly retryable: boolean; }
export interface ScoreResult { readonly modelVersion: '1.0.0'; readonly value: number | null; readonly label: 'not-assessed' | 'few-observed' | 'low' | 'moderate' | 'high' | 'critical'; readonly provisional: boolean; readonly categories: readonly { readonly category: Category; readonly raw: number; readonly cap: number; readonly deducted: number }[]; readonly groups: readonly { readonly riskKey: string; readonly findingIds: readonly string[]; readonly deducted: number }[]; readonly interpretation: SafeText; }
export interface ScanReport { readonly schemaVersion: '1.0.0'; readonly engineVersion: string; readonly rulesetVersion: '1.0.0'; readonly kind: 'scan'; readonly status: 'complete' | 'partial'; readonly scope: { readonly project: 'PROJECT'; readonly userConfigs: boolean; readonly exclusions: readonly SafeText[] }; readonly coverage: { readonly eligibleFiles: number; readonly analyzedFiles: number; readonly visitedEntries: number; readonly skippedByReason: Readonly<Record<string, number>>; readonly limitations: readonly SafeText[] }; readonly sources: readonly { readonly id: string; readonly location: Location; readonly adapter?: AgentKind }[]; readonly agents: readonly DetectedAgent[]; readonly mcpServers: readonly MCPServer[]; readonly capabilities: readonly Capability[]; readonly findings: readonly Finding[]; readonly errors: readonly ScanError[]; readonly score: ScoreResult; readonly thresholdExceeded: boolean; readonly presentation: { readonly minimumSeverity: Severity }; }
export interface ScanFailure { readonly schemaVersion: '1.0.0'; readonly engineVersion: string; readonly kind: 'failure'; readonly errors: readonly { readonly code: string; readonly message: SafeText }[]; }
export interface DoctorReport { readonly schemaVersion: '1.0.0'; readonly engineVersion: string; readonly rulesetVersion: '1.0.0'; readonly kind: 'doctor'; readonly runtimeSupported: boolean; readonly platform: string; readonly architecture: string; readonly adapters: readonly { readonly kind: AgentKind; readonly adapterVersion: '1.0.0' }[]; readonly checks: readonly { readonly id: 'escape' | 'score'; readonly state: 'pass' | 'fail'; readonly message: SafeText }[]; readonly overrides: { readonly codexHome: boolean; readonly claudeConfigDir: boolean }; }
/** `claudeProjectRoot` and `workspaceOrdinal` are acquisition-only context; neither is serialized. */
export interface SourceRecord { readonly id: string; readonly scope: Scope; readonly kind?: AgentKind; readonly relativePath: string; readonly content: string; readonly parseKind: 'json' | 'jsonc' | 'toml' | 'markdown'; readonly principalId: string; readonly claudeProjectRoot?: string; readonly workspaceOrdinal?: number; readonly parsed?: unknown; }
export interface AnalyzeResult { readonly findings: readonly Finding[]; readonly agents: readonly DetectedAgent[]; readonly mcpServers: readonly MCPServer[]; readonly capabilities: readonly Capability[]; readonly errors: readonly ScanError[]; }
