import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { readExact, ReadError } from '../../dist/src/fs/read.js';
import { walk } from '../../dist/src/fs/walk.js';
import { scanProject } from '../../dist/src/node/index.js';
import { validateAnalyzeResultDto } from '../../dist/src/parsers/pool.js';

test('readExact accumulates bounded short chunks and rejects premature EOF',async()=>{let offset=0;const chunks=[1,2,1];const good={read:async(buffer,start,length)=>{const count=Math.min(chunks.shift()??0,length);Buffer.from('test').copy(buffer,start,offset,offset+count);offset+=count;return{bytesRead:count};}};assert.equal((await readExact(good,4)).toString(),'test');await assert.rejects(readExact({read:async()=>({bytesRead:0})},1),ReadError);});
test('walk stops globally and honors abort/deadline',async()=>{const root=await mkdtemp(join(tmpdir(),'agentfence-walk-limit-'));try{for(let index=0;index<4;index++)await writeFile(join(root,`f${index}`),'x');const limited=await walk(root,{limits:{entries:2,directoryEntries:5,depth:2}});assert.equal(limited.visited,2);assert.equal(limited.skipped['entry-limit'],1);const signal=new AbortController();signal.abort();assert.equal((await walk(root,{signal:signal.signal})).skipped.interrupted,1);assert.equal((await walk(root,{deadline:0,now:()=>1})).skipped.deadline,1);}finally{await rm(root,{recursive:true,force:true});}});
test('bounded metadata inspection preserves lexical order and rejects a directory overflow as a whole',async()=>{const root=await mkdtemp(join(tmpdir(),'agentfence-walk-order-'));try{for(const name of ['z.md','a.md','m.md'])await writeFile(join(root,name),'x');const one=await walk(root),two=await walk(root);assert.deepEqual(one.files,['a.md','m.md','z.md']);assert.deepEqual(one.files,two.files);const overflow=await walk(root,{limits:{entries:10,directoryEntries:2,depth:2}});assert.equal(overflow.skipped['directory-entry-limit'],1);assert.equal(overflow.visited,2);assert.deepEqual(overflow.files,[]);}finally{await rm(root,{recursive:true,force:true});}});
test('shared project and user counters, finding cap, malformed env, and fence parsing are partial',async()=>{const root=await mkdtemp(join(tmpdir(),'agentfence-budget-')),home=await mkdtemp(join(tmpdir(),'agentfence-home-'));try{await writeFile(join(root,'.mcp.json'),'{"mcpServers":{"a":{"command":"tool"},"b":{"command":"tool"}}}');await mkdir(join(home,'.claude','rules'),{recursive:true});await writeFile(join(home,'.claude','rules','r.md'),'unterminated\n```');const report=await scanProject({path:root,userConfigs:true},{home:()=>home,limits:{files:1,findings:1}});assert.equal(report.status,'partial');assert.ok(report.coverage.eligibleFiles>=report.coverage.analyzedFiles);assert.ok(report.errors.some(error=>error.code==='AF_CANDIDATE_LIMIT'||error.code==='AF_FINDINGS_LIMIT'));const malformed=await scanProject({path:root},{limits:{files:10}});assert.equal(malformed.status,'complete');await writeFile(join(root,'.mcp.json'),'{"mcpServers":{"bad":{"command":"x","env":{"OPENAI_API_KEY":7}},"good":{"command":"y"}}}');const partial=await scanProject({path:root});assert.equal(partial.status,'partial');assert.equal(partial.mcpServers.length,1);}finally{await rm(root,{recursive:true,force:true});await rm(home,{recursive:true,force:true});}});
test('scan-wide worker finding budget stops later source analysis before allocation',async()=>{const root=await mkdtemp(join(tmpdir(),'agentfence-global-findings-')),canary='LATER_FINDING_SOURCE_CANARY';try{for(let index=0;index<4;index++){const directory=join(root,`d${index}`);await mkdir(directory);await writeFile(join(directory,'AGENTS.md'),index===3?`\u202e${canary}`:'\u202e'.repeat(4));}const report=await scanProject({path:root},{limits:{findings:10}}),serialized=JSON.stringify(report);assert.equal(report.status,'partial');assert.equal(report.findings.length,10);assert.equal(report.coverage.analyzedFiles,3);assert.equal(report.sources.length,3);assert.equal(report.coverage.eligibleFiles,4);assert.ok(report.errors.some(error=>error.code==='AF_FINDINGS_LIMIT'));assert.ok(report.errors.some(error=>error.code==='AF_REPORT_LIMIT'));assert.equal(serialized.includes(canary),false);const agentIds=new Set(report.agents.map(agent=>agent.id));for(const finding of report.findings)for(const agent of finding.agentIds)assert.ok(agentIds.has(agent));}finally{await rm(root,{recursive:true,force:true});}});
test('worker DTO validator rejects extra keys and invalid enums without raw fields',()=>{const base={findings:[],agents:[],mcpServers:[],capabilities:[],errors:[]};assert.equal(validateAnalyzeResultDto(base),true);assert.equal(validateAnalyzeResultDto({...base,extra:true}),false);assert.equal(validateAnalyzeResultDto({...base,errors:[{code:'AF_X',stage:'invalid',message:'safe',effect:'partial',retryable:false}]}),false);assert.equal(validateAnalyzeResultDto({...base,parsed:{}}),false);});
test('unterminated Markdown fence is a safe partial parse result',async()=>{const root=await mkdtemp(join(tmpdir(),'agentfence-fence-'));try{await writeFile(join(root,'AGENTS.md'),'review\n```');const report=await scanProject({path:root});assert.equal(report.status,'partial');assert.ok(report.errors.some(error=>error.code==='AF_MARKDOWN_FENCE'||error.code==='AF_PARSE_FAILED'));}finally{await rm(root,{recursive:true,force:true});}});
test('scan-wide user traversal accounts entries and turns a clock expiry into one partial timeout',async()=>{const root=await mkdtemp(join(tmpdir(),'agentfence-clock-root-')),home=await mkdtemp(join(tmpdir(),'agentfence-clock-home-'));try{await mkdir(join(home,'.claude','rules'),{recursive:true});await writeFile(join(home,'.claude','rules','r.md'),'ordinary text');let calls=0;const now=()=>++calls<15?0:2;const report=await scanProject({path:root,userConfigs:true},{home:()=>home,now,limits:{scanMs:1}});assert.equal(report.status,'partial');assert.ok(report.coverage.visitedEntries>0);assert.equal(report.errors.filter(error=>error.code==='AF_SCAN_TIMEOUT').length,1);assert.ok(report.coverage.eligibleFiles>=report.coverage.analyzedFiles);}finally{await rm(root,{recursive:true,force:true});await rm(home,{recursive:true,force:true});}});
test('reserved attempted bytes include rejected input and prevent the next body read',async()=>{const root=await mkdtemp(join(tmpdir(),'agentfence-reserve-'));try{await mkdir(join(root,'.claude','rules'),{recursive:true});await writeFile(join(root,'.claude','rules','bad.md'),Buffer.from([0,1]));await writeFile(join(root,'AGENTS.md'),'ordinary');const report=await scanProject({path:root},{limits:{bytes:3,files:4}});assert.equal(report.status,'partial');assert.ok(report.errors.some(error=>error.code==='AF_BINARY_INPUT'));assert.ok(report.errors.some(error=>error.code==='AF_TOTAL_BYTES'));assert.equal(report.coverage.eligibleFiles,2);assert.ok(report.coverage.eligibleFiles>=report.coverage.analyzedFiles);}finally{await rm(root,{recursive:true,force:true});}});
