import test from 'node:test';
import assert from 'node:assert/strict';
import { analyzeSources, scoreFindings } from '../../dist/src/core/index.js';
import { escapeTerminal } from '../../dist/src/security/safe.js';
import { validateAnalyzeResultDto } from '../../dist/src/parsers/pool.js';

test('safe terminal escaping has no controls', () => {
  assert.equal(escapeTerminal('a\u001b]52;secret\u0007\n'), 'a\\u001B]52;secret\\u0007\\u000A');
});
test('analysis projects fake secret values away', () => {
  const result = analyzeSources([{id:'S1',scope:'project',kind:'generic-mcp',relativePath:'.mcp.json',parseKind:'json',principalId:'P',content:'{"mcpServers":{"x":{"command":"npx p","env":{"OPENAI_API_KEY":"FAKE_CANARY_VALUE"}}}}'}]);
  assert.ok(result.findings.some(f => f.ruleId === 'AF-SECRET-002'));
  assert.equal(JSON.stringify(result).includes('FAKE_CANARY_VALUE'), false);
});
test('score is null without analyzed input', () => assert.equal(scoreFindings([],0).value, null));
test('public core boundary projects hostile source identifiers to structural IDs',()=>{const canary='RAW_CORE_CANARY';const result=analyzeSources([{id:canary,principalId:canary,scope:'not-a-scope',kind:'not-an-adapter',relativePath:canary,parseKind:'not-a-parser',content:`${canary}\u202e`}]);const output=JSON.stringify(result);assert.equal(output.includes(canary),false);for(const finding of result.findings){assert.match(finding.location.sourceId,/^S[1-9][0-9]*$/);assert.match(finding.principalId??'P1',/^P(?:[0-9]+|-user)?$/);}});
test('public source projection resolves ID collisions and bounds hostile structural IDs',()=>{const canary='PUBLIC_SOURCE_CANARY',base={scope:'project',relativePath:'AGENTS.md',parseKind:'markdown',content:'\u202e'};const collision=analyzeSources([{...base,id:'S2',principalId:'P2'},{...base,id:canary,principalId:canary}]);const sourceIds=collision.findings.map(finding=>finding.location.sourceId);assert.deepEqual(sourceIds,['S2','S3']);assert.equal(new Set(sourceIds).size,2);const huge=analyzeSources([{...base,id:`S${'9'.repeat(10_000)}${canary}`,principalId:`P${'9'.repeat(10_000)}${canary}`}]),serialized=JSON.stringify(huge);assert.equal(serialized.includes(canary),false);assert.ok(huge.findings.every(finding=>finding.location.sourceId.length<=5));});
test('public source count truncation is explicit rather than silent',()=>{const source=index=>({id:`S${index+1}`,scope:'project',relativePath:'AGENTS.md',parseKind:'markdown',principalId:`P${index+1}`,content:''});const result=analyzeSources(Array.from({length:1_001},(_,index)=>source(index)));assert.ok(result.errors.some(error=>error.code==='AF_REPORT_LIMIT'));assert.equal(result.errors.filter(error=>error.code==='AF_REPORT_LIMIT').length,1);});
test('package facade bounds preprocessing and retains one truncation sentinel',async()=>{const core=await import('agentfence/core'),source=index=>({id:`S${index+1}`,scope:'project',relativePath:'AGENTS.md',parseKind:'markdown',principalId:`P${index+1}`,content:''}),sources=Array.from({length:1_002},(_,index)=>source(index));Object.defineProperty(sources,1_001,{enumerable:true,get(){throw new Error('UNBOUNDED_PUBLIC_PREPROCESS');}});const result=core.analyzeSources(sources);assert.ok(result.errors.some(error=>error.code==='AF_REPORT_LIMIT'));});
test('package facade ignores unknown fields and acquisition parser metadata',async()=>{const core=await import('agentfence/core'),canary='PUBLIC_UNKNOWN_FIELD_CANARY',source={id:'S1',scope:'project',kind:'generic-mcp',relativePath:'.mcp.json',parseKind:'json',principalId:'P1',content:'{"mcpServers":{}}',parsed:{mcpServers:{hidden:{command:'tool',env:{OPENAI_API_KEY:canary}}}},unknownField:canary};const result=core.analyzeSources([source]);assert.equal(result.findings.some(finding=>finding.ruleId==='AF-SECRET-002'),false);assert.equal(JSON.stringify(result).includes(canary),false);});
test('public core detects U+202C with safe code-point-aware identity',async()=>{const core=await import('agentfence/core'),result=core.analyzeSources([{id:'S1',scope:'project',relativePath:'AGENTS.md',parseKind:'markdown',principalId:'P1',content:'a\u202Cb'}]),finding=result.findings.find(item=>item.ruleId==='AF-UNICODE-001');assert.ok(finding);assert.deepEqual(finding.evidence.codePoints,['U+202C']);assert.deepEqual([finding.location.line,finding.location.column,finding.location.endLine,finding.location.endColumn],[1,2,1,3]);assert.match(finding.id,/^[a-f0-9]{16}$/);});
test('public core rejects oversized hostile Markdown before Unicode analysis',async()=>{const core=await import('agentfence/core'),canary='PUBLIC_OVERSIZED_CANARY',result=core.analyzeSources([{id:'S1',scope:'project',relativePath:'AGENTS.md',parseKind:'markdown',principalId:'P1',content:`${canary}${'\u202e'.repeat(1_000_001)}`}]);assert.equal(result.findings.length,0);assert.ok(result.errors.some(error=>error.code==='AF_OVERSIZED_INPUT'));assert.equal(JSON.stringify(result).includes(canary),false);});
test('public core caps Unicode allocation at the global finding limit with deterministic retained coordinates',async()=>{const core=await import('agentfence/core'),result=core.analyzeSources([{id:'S1',scope:'project',relativePath:'AGENTS.md',parseKind:'markdown',principalId:'P1',content:'\u202e'.repeat(349_525)}]),columns=result.findings.map(finding=>finding.location.column).sort((a,b)=>a-b);assert.equal(result.findings.length,10_000);assert.ok(result.errors.some(error=>error.code==='AF_REPORT_LIMIT'));assert.equal(validateAnalyzeResultDto(result),true);assert.deepEqual([columns[0],columns.at(-1)],[1,10_000]);assert.equal(JSON.stringify(result).includes('PUBLIC_UNICODE_CANARY'),false);});
test('public core stops before cumulative accepted content exceeds 32 MiB',async()=>{const core=await import('agentfence/core'),oneMiB='x'.repeat(1_024*1_024),canary='PUBLIC_TOTAL_BYTES_CANARY',sources=Array.from({length:32},(_,index)=>({id:`S${index+1}`,scope:'project',relativePath:'AGENTS.md',parseKind:'markdown',principalId:`P${index+1}`,content:oneMiB}));sources.push({id:'S33',scope:'project',relativePath:'AGENTS.md',parseKind:'markdown',principalId:'P33',content:`\u202e${canary}`});const result=core.analyzeSources(sources);assert.equal(result.findings.length,0);assert.ok(result.errors.some(error=>error.code==='AF_TOTAL_BYTES'&&error.sourceId==='S33'));assert.equal(validateAnalyzeResultDto(result),true);assert.equal(JSON.stringify(result).includes(canary),false);});
test('package core facade excludes internal raw-DT0 helpers and strips acquisition ordinals',async()=>{const core=await import('agentfence/core');assert.equal('prepareSources'in core,false);assert.equal('mergeAnalysisResults'in core,false);const result=core.analyzeSources([{id:'S1',scope:'project',kind:'codex',relativePath:'.codex/config.toml',parseKind:'toml',principalId:'P1',workspaceOrdinal:9007199254740991,content:'[mcp_servers.one]\ncommand = "tool"'},{id:'S2',scope:'project',kind:'codex',relativePath:'packages/x/.codex/config.toml',parseKind:'toml',principalId:'P2',workspaceOrdinal:7,content:'[mcp_servers.one]\ncommand = "tool"'}]);assert.deepEqual(result.agents.map(agent=>agent.id).sort(),['A-codex-S0','A-codex-S1']);assert.equal(JSON.stringify(result).includes('9007199254740991'),false);});
