import test from 'node:test';
import assert from 'node:assert/strict';
import { terminalReport } from '../../dist/src/reporters/terminal.js';

const finding=(id,severity,sourceId,line,ruleId)=>({id,ruleId,ruleVersion:'1.0.0',title:'title',severity,category:'shell',description:'unsafe\u001b]52;canary',evidence:{kind:'field',summary:'summary',factIds:['F-0123456789abcdef']},location:{sourceId,scope:'project',displayPath:'source-1',line,column:1},relatedLocations:[],recommendation:'review\ncarefully',confidence:'high',applicability:'potential',agentIds:['A-cursor-S0'],riskKey:`shell:${id}`,references:[],relatedFindingIds:[]});
const report=(findings=[],score=100,status='complete')=>({schemaVersion:'1.0.0',engineVersion:'0.1.0',rulesetVersion:'1.0.0',kind:'scan',status,scope:{project:'PROJECT',userConfigs:false,exclusions:[]},coverage:{eligibleFiles:2,analyzedFiles:2,visitedEntries:3,skippedByReason:{},limitations:['limit\u001b]52;canary']},sources:[],agents:[{id:'A-cursor-S0',kind:'cursor',detection:'confirmed-config',sources:['S1'],adapterVersion:'1.0.0',runtimeVersion:'unknown',effectiveState:'unverified'}],mcpServers:[],capabilities:[],findings,errors:[],score:score===null?{modelVersion:'1.0.0',value:null,label:'not-assessed',provisional:false,categories:[],groups:[],interpretation:'none'}:{modelVersion:'1.0.0',value:score,label:'low',provisional:status==='partial',categories:[],groups:[],interpretation:'none'},thresholdExceeded:false,presentation:{minimumSeverity:'info'}});

test('terminal report has required sections, safe text, and severity/source ordering',()=>{const r=report([finding('1','high','S2',4,'AF-Z-001'),finding('2','critical','S3',1,'AF-B-001'),finding('3','high','S1',9,'AF-A-001')]);const text=terminalReport(r,false);assert.ok(text.indexOf('AgentFence complete scan')<text.indexOf('Agent configuration inventory:'));assert.ok(text.indexOf('Agent configuration inventory:')<text.indexOf('Score:'));assert.ok(text.indexOf('Score:')<text.indexOf('Findings:'));assert.ok(text.indexOf('Errors and limitations:')<text.indexOf('Summary:'));assert.ok(text.indexOf('CRITICAL AF-B-001')<text.indexOf('HIGH AF-A-001'));assert.ok(text.indexOf('HIGH AF-A-001')<text.indexOf('HIGH AF-Z-001'));assert.equal(text.includes('\u001b'),false);assert.ok(text.includes('confidence high applicability potential'));assert.ok(text.includes('Recommendation: review\\u000Acarefully'));});
test('terminal exact empty wording and filtering are explicit',()=>{assert.ok(terminalReport(report([],null)).includes('No supported configuration assessed'));const r=report([finding('1','low','S1',1,'AF-X-001')]);r.presentation.minimumSeverity='high';assert.ok(terminalReport(r).includes('No findings in assessed scope'));});
test('terminal color wraps severity labels only when caller enables it',()=>{const r=report([finding('1','high','S1',1,'AF-X-001')]);const plain=terminalReport(r,false),colored=terminalReport(r,true);assert.equal(plain.includes('\u001b['),false);assert.ok(colored.includes('\u001b[31mHIGH\u001b[0m'));assert.equal(colored.includes('\u001b[31mAF-X-001'),false);});
test('terminal compares coordinates numerically before rule and ID ties',()=>{const r=report([finding('z','high','S1',10,'AF-A-001'),finding('b','high','S1',2,'AF-Z-001'),finding('a','high','S1',2,'AF-A-001')]);const text=terminalReport(r);assert.ok(text.indexOf('AF-A-001 S1:2:1')<text.indexOf('AF-Z-001 S1:2:1'));assert.ok(text.indexOf('AF-Z-001 S1:2:1')<text.indexOf('AF-A-001 S1:10:1'));});
test('terminal omits unavailable finding coordinates instead of rendering zeros',()=>{const unlocated={...finding('none','high','S1',1,'AF-X-001'),location:{...finding('none','high','S1',1,'AF-X-001').location,line:undefined,column:undefined}};const text=terminalReport(report([unlocated]));assert.ok(text.includes('AF-X-001 S1 confidence'));assert.equal(text.includes('S1:0:0'),false);});
