import { constants } from 'node:fs';
import { open, lstat } from 'node:fs/promises';
import { isAbsolute, join, relative } from 'node:path';
import { LIMITS } from '../application/budget.js';
export class ReadError extends Error { constructor(readonly code:'AF_READ_REJECTED'|'AF_FILE_CHANGED'|'AF_BINARY_INPUT'|'AF_OVERSIZED_INPUT'|'AF_LINK_INPUT'|'AF_TOTAL_BYTES'){super(code);} }
function segments(relativePath:string):string[]{if(!relativePath||isAbsolute(relativePath)||relativePath.split(/[\\/]/).some(part=>part===''||part==='.'||part==='..'))throw new ReadError('AF_READ_REJECTED');return relativePath.split(/[\\/]/);}
type Identity={readonly path:string;readonly dev:number;readonly ino:number;readonly kind:'file'|'directory'};
export interface CheckedPathOptions { readonly lstat?:typeof lstat; }
async function checkedPath(root:string,relativePath:string,kind:'file'|'directory',options:CheckedPathOptions={}):Promise<{path:string;entry:Awaited<ReturnType<typeof lstat>>;rootDevice:number;identities:readonly Identity[]}>{const statPath=options.lstat??lstat,parts=segments(relativePath);let current=root;let rootStat;try{rootStat=await statPath(root);}catch{throw new ReadError('AF_READ_REJECTED');}if(rootStat.isSymbolicLink())throw new ReadError('AF_LINK_INPUT');if(!rootStat.isDirectory())throw new ReadError('AF_READ_REJECTED');const identities:Identity[]=[{path:root,dev:rootStat.dev,ino:rootStat.ino,kind:'directory'}];for(let index=0;index<parts.length;index++){current=join(current,parts[index]!);let entry;try{entry=await statPath(current);}catch{throw new ReadError('AF_READ_REJECTED');}if(entry.isSymbolicLink())throw new ReadError('AF_LINK_INPUT');if(entry.dev!==rootStat.dev)throw new ReadError('AF_READ_REJECTED');const expected=index<parts.length-1?'directory':kind;if(expected==='file'?!entry.isFile():!entry.isDirectory())throw new ReadError('AF_READ_REJECTED');identities.push({path:current,dev:entry.dev,ino:entry.ino,kind:expected});if(index<parts.length-1)continue;const containment=relative(root,current);if(!containment||containment.startsWith('..')||isAbsolute(containment))throw new ReadError('AF_READ_REJECTED');return{path:current,entry,rootDevice:rootStat.dev,identities};}throw new ReadError('AF_READ_REJECTED');}
async function verifyIdentities(identities:readonly Identity[],rootDevice:number,statPath:typeof lstat):Promise<void>{for(const identity of identities){let entry;try{entry=await statPath(identity.path);}catch{throw new ReadError('AF_FILE_CHANGED');}if(entry.isSymbolicLink()||entry.dev!==rootDevice||entry.dev!==identity.dev||entry.ino!==identity.ino||(identity.kind==='file'?!entry.isFile():!entry.isDirectory()))throw new ReadError('AF_FILE_CHANGED');}}
export async function checkedDirectory(root:string,relativePath:string,options:CheckedPathOptions={}):Promise<void>{await checkedPath(root,relativePath,'directory',options);}
type ReadHandle={read(buffer:Buffer,offset:number,length:number,position:number):Promise<{bytesRead:number}>};
/** Read a verified snapshot completely; a short EOF is a change, never partial input. */
export async function readExact(handle:ReadHandle,expected:number):Promise<Buffer>{const data=Buffer.alloc(expected);let offset=0;while(offset<expected){const {bytesRead}=await handle.read(data,offset,expected-offset,offset);if(!Number.isSafeInteger(bytesRead)||bytesRead<=0||bytesRead>expected-offset)throw new ReadError('AF_FILE_CHANGED');offset+=bytesRead;}const extra=Buffer.alloc(1);const trailing=await handle.read(extra,0,1,expected);if(trailing.bytesRead!==0)throw new ReadError('AF_FILE_CHANGED');return data;}
export interface CheckedReadOptions extends CheckedPathOptions { readonly reserveBytes?:(size:number)=>boolean; readonly afterRead?:()=>void|Promise<void>; }
export async function checkedRead(root:string, relativePath:string,options:CheckedReadOptions={}):Promise<string>{const statPath=options.lstat??lstat,checked=await checkedPath(root,relativePath,'file',{lstat:statPath});const pre=checked.entry,preSize=Number(pre.size);if(!Number.isSafeInteger(preSize)||preSize<0)throw new ReadError('AF_READ_REJECTED');if(options.reserveBytes&&options.reserveBytes(preSize)===false)throw new ReadError('AF_TOTAL_BYTES');if(pre.nlink>1)throw new ReadError('AF_READ_REJECTED');if(preSize>LIMITS.fileBytes)throw new ReadError('AF_OVERSIZED_INPUT');const flags=constants.O_RDONLY | (constants.O_NOFOLLOW ?? 0) | (constants.O_NONBLOCK ?? 0);let fh;try{fh=await open(checked.path,flags);}catch{throw new ReadError('AF_READ_REJECTED');}try{const before=await fh.stat(),expected=Number(before.size);if(!Number.isSafeInteger(expected)||expected<0||!before.isFile()||before.nlink>1||before.ino!==pre.ino||before.dev!==pre.dev||before.dev!==checked.rootDevice||before.size!==pre.size)throw new ReadError('AF_FILE_CHANGED');const body=await readExact(fh,expected);await options.afterRead?.();if(body.includes(0))throw new ReadError('AF_BINARY_INPUT');const decoded=new TextDecoder('utf-8',{fatal:true}).decode(body);const after=await fh.stat();if(after.ino!==before.ino||after.dev!==before.dev||after.dev!==checked.rootDevice||after.size!==before.size||after.mtimeMs!==before.mtimeMs)throw new ReadError('AF_FILE_CHANGED');await verifyIdentities(checked.identities,checked.rootDevice,statPath);return decoded.charCodeAt(0)===0xfeff?decoded.slice(1):decoded;}catch(error){if(error instanceof ReadError)throw error;throw new ReadError('AF_READ_REJECTED');}finally{await fh.close();}}
